# Generated by Django 5.0.1 on 2024-01-29 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('date_applied', models.DateField(blank=True, default=datetime.date.today)),
                ('contact_info', models.CharField(blank=True, max_length=50)),
                ('application_status', models.CharField(default='APPLIED', max_length=25)),
            ],
        ),
    ]
