# Generated by Django 5.0.1 on 2024-01-30 02:22

import job_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100, validators=[job_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=100, validators=[job_app.validators.validate_name]),
        ),
    ]
