# Generated by Django 5.0.1 on 2024-01-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_alter_job_company_name_alter_job_job_name'),
        ('tracker_app', '0002_alter_tracker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='tracker_app.tracker'),
        ),
    ]
