# Generated by Django 5.0.1 on 2024-01-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker_library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='tracker_library_app.trackerlibrary')),
            ],
        ),
    ]
